### ISSUE TITLE
overloads

### ISSUE THREAD

**Issue by neboskrebnut** [broflowsky/coen244A3#1]
test test 1 2 3
Operator overloads should be in the same type of files (.h or .cpp)

And customer and Car needs access to the pointers of each other.

**Comment by neboskrebnut** [comment]
look at this. more places to spam and discuss work without actually doing it.

**Comment by neboskrebnut** [comment]
I'll work on this tomorrow 22/02/18 around 9-10AM

**Comment by broflowsky** [comment]
wow
Im working on it right now
Figuring out some stuff
I try to answer to your comments

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by broflowsky** [comment]
I added a getters for the pointer in Car and in Customer

**Comment by broflowsky** [comment]
issue is now part of general cleanup
