### ISSUE TITLE
returnCar()

### ISSUE THREAD

**Issue by broflowsky** [broflowsky/coen244A3#5]
it s a mess, bro

you start by creating a pointing using &customer->getCar() which is fine
but then you test if that newly created pointer == &customer->getCar()
so the first if will always be true
The rest of the function doesnt make sense either

My advice is start from scratch.

**Comment by neboskrebnut** [comment]
well the second if statement might be redundant, you're right. But the idea was to check if the relations between the car and customer is valid.
I'll clean it up. but most of it is there to see if the car that we returning from the customer is actually assigned to that customer.

p.s. returnCar means return it to the company, releasing from the customer? right?

**Comment by broflowsky** [comment]
no no, re read what you wrote.
The other ifs will never happen because you essentially wrote this 
int a = b;
if (a==b)
...

the logic is flawed.
Also, look at carRentalmanagement.h i layed out the key steps the function should perform

**Comment by broflowsky** [comment]
and test the function you re writing before moving on to another one
